#!/usr/bin/env python

import sys
import traceback
from irclogs import highlight
from irclogs.utils import config, path

def main(file, config):
    print highlight(file, **config)

def print_usage(stream, program, *arguments):
    print >> stream, 'usage: %s <log-file>' % path.basename(program)

if __name__ == '__main__':

    if len(sys.argv) != 2:
        print_usage(sys.stderr, *sys.argv)
        exit(2)

    main(sys.argv[1], config.load_file(path.resolve(path.dirname(__file__), './config.json')))